version: "3"
services:
  client:
    restart: always
    build:
      context: .
      dockerfile: ./client/dockerfile
    volumes:
      - ./client:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    environment:
      HOST_URL: http://localhost:3561
  server:
    restart: always
    build:
      context: .
      dockerfile: ./server/dockerfile
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    expose:
      - 3561
    command: npm start
    environment:
      DB_URL: postgres://ijcxjhryrjtdea:943ca728598acba6554c74e137295f196096780b32f7067ab0a825a8b9ec5e0c@ec2-54-243-184-111.compute-1.amazonaws.com:5432/d3jc5i1p0kjj1v
      WS_PORT: 3561
  nginx:
    image: nginx
    volumes:
      - ./client/public:/var/www/public
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3561:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
# server доступен только в докеровской сети (expose, нет ports)
# наружу прокинут только порт nginx (ports)
# в настройках nginx запросы по сокетам перенапрявляются на app,
# а на остальные запросы отдается папка client/public
