version: "3"
services:
  client:
    restart: always
    build:
      context: .
      dockerfile: ./client/dockerfile
    volumes:
      - ./client:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_ENV: production
      HOST_URL: http://monkk.ru/chess/ws
    command: npm start
  server:
    restart: always
    build:
      context: .
      dockerfile: ./server/dockerfile
    volumes:
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    expose:
      - 3562
    environment:
      WS_PORT: 3562
      DB_URL: postgres://ijcxjhryrjtdea:943ca728598acba6554c74e137295f196096780b32f7067ab0a825a8b9ec5e0c@ec2-54-243-184-111.compute-1.amazonaws.com:5432/d3jc5i1p0kjj1v
    command: npm start
  nginx:
    image: nginx
    volumes:
      - ./client/public:/var/www/public
      - ./nginx.staging.conf:/etc/nginx/nginx.conf
    ports:
      - "3562:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
