version: "3"
services:
  client:
    environment:
      NODE_ENV: production
      HOST_URL: http://monkk.ru/chess/ws
    command: npm start
  server:
    expose:
      - 3562
    environment:
      WS_PORT: 3562
    command: npm start
  nginx:
    volumes:
      - ./client/public:/var/www/public
      - ./nginx.staging.conf:/etc/nginx/nginx.conf
    ports:
      - "3562:80"
