version: '3'
services:
  watch:
    container_name: watcher
    build: ./client/
    volumes:
      - ./client:/usr/src/app/local_client
    # depends_on:
    #   - web
    # volumes_from:
    #   - docker-chess-node
    # working_dir: /usr/src/app
    # command: docker run --rm -v c:/Users:/data alpine ls /data
  
  app:
    container_name: docker-chess-node
    restart: always
    build: ./server/
    volumes:
      - ./client/public:/usr/src/app/client/public
      - ./server:/usr/src/app/local_server
    ports:
      - '3561:3561'

  