version: '3'
services:
  watch:
    container_name: watcher
    build: ./client/
    volumes:
      - ./client:/usr/src/app/local_client
    # depends_on:
    #   - web
    # volumes_from:
    #   - docker-chess-node
    # working_dir: /usr/src/app
    # command: docker run --rm -v c:/Users:/data alpine ls /data
  
  
  web:
    image: nginx
    volumes:
    - ./client/public:/app
    - ./nginx.conf:/etc/nginx/nginx.conf
    # - ./config.txt:/etc/nginx/conf.d/default.conf
    ports:
    - "3561:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  app:
    container_name: docker-chess-node
    restart: always
    build: ./server/
    volumes:
      - ./client/public:/usr/src/app/client/public
      - ./server:/usr/src/app/local_server
    expose:
      - 3561


# app  доступен только в докеровской сети (expose, нет ports)
# наружу прокинут только порт nginx (ports)
# в настройках nginx запросы по сокетам перенапрявляются на app,
# а на остальные запросы отдается папка client/public 